### ISSUE TITLE
Generation is broken for view function without returns

### ISSUE THREAD

**Issue by robgsupsi** [inveker/web3dart_builders#9]
I noticed that the code generation is broken whenever an abi that contains an immutable function without returns is provided.
The build_runner execution returns the following error: 

Bad state: No element

I tracked down the problem and it should be in the `_bodyForImmutable` function of the **generator.dart** file, around line 250. The case with outputs.length == 0 is not managed.

**Comment by inveker** [comment]
@robgsupsi, can you send me an abi example?

**Comment by robgsupsi** [comment]
For sure, here it is:

`[
    {
        "inputs": [
            {
                "internalType": "uint256",
                "name": "tokenId",
                "type": "uint256"
            },
            {
                "internalType": "string",
                "name": "serviceType",
                "type": "string"
            },
            {
                "internalType": "string",
                "name": "serviceId",
                "type": "string"
            }
        ],
        "name": "verifyServiceOwnership",
        "outputs": [],
        "stateMutability": "view",
        "type": "function"
    }
]`

**Comment by inveker** [comment]
@robgsupsi, It seems to me that creating view functions without a return value is pointless, can you tell us more about your use case?

**Comment by robgsupsi** [comment]
I do not agree that it is pointless. Let's say you want to have a function that contains logic to check some conditions and possibly launches different kind of exceptions depending on the error. If no exception is raised then all the checks are passed and the functions finished the execution correctly. That would not require the view function to return a value.

**Comment by inveker** [comment]
@robgsupsi, If you want to decompose a more complex view function, for example, not to show data to everyone (although they will be able to read the data anyway, the truth is more complicated - after all, there is getStorageAt). Then you really need to have a function view without a return value, in which case you can make this sub-function internal - so it will not fall into the abi, since this does not make sense, public view functions are intended to be read anyway.

For example:
```solidity
function myFun() public view returns(address) {
  isRequired();
  return msg.sender;
}

function isRequired() internal view {
  require(false, "Not required!");
}
```

**Comment by robgsupsi** [comment]
@inveker I see your point, but imagine that your `isRequired` method that just contain some rules is called by another Smart Contract, not inheriting from this one. In that case you cannot make it internal. Although it is true that it will never be called directly by the dart code, the generation still breaks since it is not yet supported (but allowed by the language).

**Comment by inveker** [comment]
@robgsupsi 

After talking with the community, we came to the conclusion that such functions have a place to be, I think it's worth including this in the web3dart_builders library. Tell me, can you participate in the development of this feature?

**Comment by inveker** [comment]
@robgsupsi, New version released - 0.0.6, please check

**Comment by robgsupsi** [comment]
@inveker thanks a lot, I just tested it now with one of my contracts and the generation now works fine.

**Comment by inveker** [comment]
@robgsupsi Great, I'll close the issue then.
